### ISSUE TITLE
Rename and move to DG org

### ISSUE THREAD

**Issue by scottcorgan** [shanebo/suiter#2]
I'd like to propose we rename the library and move it to the DG org, for the sake of finding things 👍 

I'd like to name it more descriptive of what it does like `element-breakpoints`

**Comment by shanebo** [comment]
@scottcorgan good proposal to consider. A few thoughts, this project was born out of a problem that we have, but it's not unique to us per say. So I wanted to open source this without it taxing us at DG long-term so I wrote it on my own dime. But let's continue the convo...

**Comment by scottcorgan** [comment]
Cool. It's not a big deal for me where this is, but I would recommend naming it something that is more descriptive. It's really hard to find stuff in JS-land because people name things that are metaphors or whatever thesaurus.com throws at them (I'm guilty of that).

Examples:

* React
* Angular
* Mocha
* Chai
* etc.

👍

**Comment by shanebo** [comment]
Yeah I hear you. I'm a fan of the concise/funny type names because the js community is a fun/weird place... but in terms of how naming applies to our codebase, I was planning on adding support for custom data attribute selectors for the queries and classes. So instead of `data-suiter-queries` and `data-suiter-classes` you could pass in say `data-responsive-queries` and `data-responsive-classes` to be used, or whatever you wanted for that matter. In other words, I didn't intend on us using `data-suiter-...` in our DG markup.

Does that resonate with you?

**Comment by scottcorgan** [comment]
I'm cool with whatever

**Comment by scottcorgan** [comment]
Ah, and fyi, https://www.npmjs.com/package/suiter

**Comment by shanebo** [comment]
@scottcorgan yeah I saw that when I created it. Are we package managing via npm for frontend assets?

**Comment by scottcorgan** [comment]
I hope so. The only alternative is Bower, that's mostly abandoned. Especially since we're use Webpack, it'll bundle modules based off the `main` key in `package.json`

**Comment by shanebo** [comment]
Cool. I'll refactor some name things, submit a PR so you can review, and then I'll grab that package on npm...
